spring:
  application:
    name: zuul-gateway-service
  cloud:
    config:
      uri:
      - http:localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5555
  
# management:
#   endpoints:
#     web:
#       exposure:
#         include: *
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"